# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
matrix:
  allow_failures:
    - python: 3.8-dev

install: pip install poetry; poetry install

script: poetry run coverage run --source gconfigs -m pytest tests/
after_success:
  - coveralls
notifications:
  on_success: change
  on_failure: always
