# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.7

install: pip install poetry; poetry install

script: poetry run coverage run --source gconfigs -m pytest tests/
after_success:
  - coveralls
notifications:
  on_success: change
  on_failure: always
