# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

install: pip install pipenv; pipenv install --dev

script: pipenv run pytest
after_success:
  - coveralls
notifications:
  on_success: change
  on_failure: always
